### ISSUE TITLE
Not able to open xll in excel

### ISSUE THREAD

**Issue by poongodimsa** [RuneLjungmann/excelbind#2]
Hi RuneLjungmann,
I am trying to open excelbind.xll in excel 2013 x64 version. I have python 3.9 x64 version installed. I repeatedly get 'The file format and extension of 'excelbind.xll' does not match...' error. The env PATH is set. .conf file placed in user folder. I dont know what I am missing. Please help.

Note: Iam able to run pyxll successfully.

Thank you,
Poongodi

**Comment by poongodimsa** [comment]
Looks like excelbind supports python 3.7 and not 3.9. I chaged the version of python and the issue sorted out.

**Comment by RuneLjungmann** [comment]
Hi

You are absolutely right. The xll's are build with python 3.7. The 'file format...' error is a standard (but slightly misleading) Excel error message, when one of the dependencies for the xll is missing. In this case most likely the python 3.7 dll.

Glad it worked out for you building it from scratch.

best regards
Rune
