### ISSUE TITLE
 unable to find the excelbind Python package

### ISSUE THREAD

**Issue by gnyuan** [RuneLjungmann/excelbind#4]
Dear Rune Ljungmann,

I am unable to find the `excelbind` Python package. Is it located in a different location?

Thank you for your time,
Yuan

**Comment by RuneLjungmann** [comment]
Hi

There is no excelbind python package as such. Excelbind is an embedded python interpreter running inside an xll, so it is available from Excel. The 'excelbind' module, is always available in this embedded interpreter - so no need for an extra python package.
For details on where this happens, see e.g. the end of https://github.com/RuneLjungmann/excelbind/blob/master/src/excelbind/function_registration.cpp and https://github.com/RuneLjungmann/excelbind/blob/master/src/excelbind/script_manager.cpp, where the excelbind module functionality is registered and created

**Comment by gnyuan** [comment]
Thank you for your kind reply! I am not familiar with pybind11, so confused about it at first glance. Perhaps it would be better to create an empty implementation of ExcelBind for debugging Python files.

**Comment by RuneLjungmann** [comment]
Hi,
Good point, but since the python side is limited, it might be easier for you to simply create a mock of the module dynamically for your testing. Maybe something like:

```
import types
import sys

def create_excelbind_mock():
    def function_mock(*args, **kwargs):
        return args[0]

    excelbind_mock = types.ModuleType('excelbind')
    excelbind_mock.function = function_mock

    sys.modules.setdefault('excelbind', excelbind_mock)

```

and then you can write stuff like:
```
create_excelbind_mock()
import excelbind

@excelbind.function
def test_fct(x):
    return x*x

print(test_fct(2))

```
